# Testcomponent code
TACLEBENCH_INSERTSORT_DIR=taclebench-components/insertsort/

TACLEBENCH_INSERTSORT_SOURCES_CC = insertsort.cc TacleinsertsortComponent.cc
TACLEBENCH_INSERTSORT_SOURCES_ASM = 
TACLEBENCH_INSERTSORT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_INSERTSORT_DIR)%o,$(TACLEBENCH_INSERTSORT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_INSERTSORT_DIR)%.oS,$(TACLEBENCH_INSERTSORT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_INSERTSORT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_INSERTSORT_OBJECTS)

CFLAGS += -DTACLE_INSERTSORT