# Testcomponent code
TACLEBENCH_BSORT_DIR=taclebench-components/bsort/

TACLEBENCH_BSORT_SOURCES_CC = bsort.cc TacleBsortComponent.cc
TACLEBENCH_BSORT_SOURCES_ASM = 
TACLEBENCH_BSORT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_BSORT_DIR)%o,$(TACLEBENCH_BSORT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_BSORT_DIR)%.oS,$(TACLEBENCH_BSORT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_BSORT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_BSORT_OBJECTS)

CFLAGS += -DTACLE_BSORT