# Testcomponent code
TACLEBENCH_LUDCMP_DIR=taclebench-components/ludcmp/

TACLEBENCH_LUDCMP_SOURCES_CC = ludcmp.cc TacleludcmpComponent.cc
TACLEBENCH_LUDCMP_SOURCES_ASM = 
TACLEBENCH_LUDCMP_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_LUDCMP_DIR)%o,$(TACLEBENCH_LUDCMP_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_LUDCMP_DIR)%.oS,$(TACLEBENCH_LUDCMP_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_LUDCMP_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_LUDCMP_OBJECTS)

CFLAGS += -DTACLE_LUDCMP