# Testcomponent code
TACLEBENCH_FFT_DIR=taclebench-components/fft/

TACLEBENCH_FFT_SOURCES_CC = fft.cc fft_input.cc TacleFftComponent.cc
TACLEBENCH_FFT_SOURCES_ASM = 
TACLEBENCH_FFT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_FFT_DIR)%o,$(TACLEBENCH_FFT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_FFT_DIR)%.oS,$(TACLEBENCH_FFT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_FFT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_FFT_OBJECTS)

CFLAGS += -DTACLE_FFT