# Testcomponent code
TACLEBENCH_FAC_DIR=taclebench-components/fac/

TACLEBENCH_FAC_SOURCES_CC = fac.cc TacleFacComponent.cc
TACLEBENCH_FAC_SOURCES_ASM = 
TACLEBENCH_FAC_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_FAC_DIR)%o,$(TACLEBENCH_FAC_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_FAC_DIR)%.oS,$(TACLEBENCH_FAC_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_FAC_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_FAC_OBJECTS)

CFLAGS += -DTACLE_FAC