# Testcomponent code
TACLEBENCH_PRIME_DIR=taclebench-components/prime/

TACLEBENCH_PRIME_SOURCES_CC = prime.cc TacleprimeComponent.cc
TACLEBENCH_PRIME_SOURCES_ASM = 
TACLEBENCH_PRIME_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_PRIME_DIR)%o,$(TACLEBENCH_PRIME_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_PRIME_DIR)%.oS,$(TACLEBENCH_PRIME_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_PRIME_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_PRIME_OBJECTS)

CFLAGS += -DTACLE_PRIME