###############################
# X86 cache management compile units #
###############################
X86_CACHEMANAGEMENT_DIR=arch/x86/cachemanagement/
X86_CACHEMANAGEMENT_SOURCES_CC = X86CacheManagement.cc X86CacheColoring.cc
X86_CACHEMANAGEMENT_SOURCES_ASM = 
X86_CACHEMANAGEMENT_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(X86_CACHEMANAGEMENT_DIR)%.o,$(X86_CACHEMANAGEMENT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(X86_CACHEMANAGEMENT_DIR)%.oS,$(X86_CACHEMANAGEMENT_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(X86_CACHEMANAGEMENT_OBJECTS)
LINKER_OBJECTS += $(X86_CACHEMANAGEMENT_OBJECTS)