# Testcomponent code
TACLEBENCH_QUICKSORT_DIR=taclebench-components/quicksort/

TACLEBENCH_QUICKSORT_SOURCES_CC = input.cc quicksort.cc quicksortlibm.cc quicksortstdlib.cc TaclequicksortComponent.cc
TACLEBENCH_QUICKSORT_SOURCES_ASM = 
TACLEBENCH_QUICKSORT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_QUICKSORT_DIR)%o,$(TACLEBENCH_QUICKSORT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_QUICKSORT_DIR)%.oS,$(TACLEBENCH_QUICKSORT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_QUICKSORT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_QUICKSORT_OBJECTS)

CFLAGS += -DTACLE_QUICKSORT