###############################
# ARMv7 driver compile units #
###############################
OMAP4460_DRIVER_BASE_DIR=arch/armv7/omap4460/driver/
OMAP4460_DRIVER_BASE_SOURCES_CC = OMAPUartDriver.cc OSC_PandaBoardLED.cc OSCOMAP4460ClockManagement.cc
OMAP4460_DRIVER_BASE_SOURCES_ASM = 
OMAP4460_DRIVER_BASE_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(OMAP4460_DRIVER_BASE_DIR)%.o,$(OMAP4460_DRIVER_BASE_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(OMAP4460_DRIVER_BASE_DIR)%.oS,$(OMAP4460_DRIVER_BASE_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(OMAP4460_DRIVER_BASE_OBJECTS)
LINKER_OBJECTS += $(OMAP4460_DRIVER_BASE_OBJECTS)