# Testcomponent code
TACLEBENCH_SHA_DIR=taclebench-components/sha/

TACLEBENCH_SHA_SOURCES_CC = sha.cc TacleshaComponent.cc
TACLEBENCH_SHA_SOURCES_ASM = 
TACLEBENCH_SHA_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_SHA_DIR)%o,$(TACLEBENCH_SHA_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_SHA_DIR)%.oS,$(TACLEBENCH_SHA_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_SHA_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_SHA_OBJECTS)

CFLAGS += -DTACLE_SHA