# Event handling code
INTERRUPTS_DIR=interrupts/
INTERRUPTS_SOURCES_CC = InterruptDispatcher.cc
INTERRUPTS_SOURCES_ASM = 
INTERRUPTS_OBJECTS = $(patsubst %o,$(OBJDIR)/$(INTERRUPTS_DIR)%o,$(INTERRUPTS_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(INTERRUPTS_DIR)%.oS,$(INTERRUPTS_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(INTERRUPTS_OBJECTS)
LINKER_OBJECTS += $(INTERRUPTS_OBJECTS)