# Testcomponent code
TACLEBENCH_MINVER_DIR=taclebench-components/minver/

TACLEBENCH_MINVER_SOURCES_CC = minver.cc TacleminverComponent.cc
TACLEBENCH_MINVER_SOURCES_ASM = 
TACLEBENCH_MINVER_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_MINVER_DIR)%o,$(TACLEBENCH_MINVER_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_MINVER_DIR)%.oS,$(TACLEBENCH_MINVER_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_MINVER_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_MINVER_OBJECTS)

CFLAGS += -DTACLE_MINVER