# Testcomponent code
TACLEBENCH_MD5_DIR=taclebench-components/md5/

TACLEBENCH_MD5_SOURCES_CC = md5.cc Taclemd5Component.cc
TACLEBENCH_MD5_SOURCES_ASM = 
TACLEBENCH_MD5_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_MD5_DIR)%o,$(TACLEBENCH_MD5_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_MD5_DIR)%.oS,$(TACLEBENCH_MD5_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_MD5_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_MD5_OBJECTS)

CFLAGS += -DTACLE_MD5