/*
 * cortexa9_interrupt_tables.h
 *
 *  Created on: 11.11.2016
 *      Author: hendrik
 */

#ifndef ARCH_ARMV7_CORTEXA9_COMMON_CORTEXA9_INTERRUPT_TABLES_H_
#define ARCH_ARMV7_CORTEXA9_COMMON_CORTEXA9_INTERRUPT_TABLES_H_


enum SW_INTERRUPTS {
	SW_INT_TEST,
	SW_INT_CACHECONTROL,
	SW_INT_STACKTRACE
};
#define NR_SW_INTERRUPTS 16

/* Cortex-A9 MPCore TRM p. 49 */
enum PPI_INTERRUPTS {
	PPI_INT_RESERVED_0 = 16,
	PPI_INT_RESERVED_1 = 17,
	PPI_INT_RESERVED_2 = 18,
	PPI_INT_RESERVED_3 = 19,
	PPI_INT_RESERVED_4 = 20,
	PPI_INT_RESERVED_5 = 21,
	PPI_INT_RESERVED_6 = 22,
	PPI_INT_RESERVED_7 = 23,
	PPI_INT_RESERVED_8 = 24,
	PPI_INT_RESERVED_9 = 25,
	PPI_INT_GX_IRQ = 26,
	PPI_INT_GLOBAL_TIMER = 27,
	PPI_INT_LX_IRQ = 28,
	PPI_INT_PRIVATE_TIMER = 29,
	PPI_INT_RESERVED_14 = 30,
	PPI_INT_RESERVED_15 = 31,
	PPI_INT_LAST,
};
#define NR_PPI_INTERRUPTS (PPI_INT_LAST - 16)


#endif /* ARCH_ARMV7_CORTEXA9_COMMON_CORTEXA9_INTERRUPT_TABLES_H_ */
