/*
 * omap4460_interrupt_table.h
 *
 *  Created on: 23.07.2015
 *      Author: hendrik
 */

#ifndef ARCH_OMAP4460_EXYNOS_INTERRUPT_TABLE_H_
#define ARCH_OMAP4460_EXYNOS_INTERRUPT_TABLE_H_

/* Include the generic Cortex-A9 interrupts here */
#include <common/cortexa9_interrupt_tables.h>

/*
 * Interrupt table for omap4460 processor.
 * omap4460 TRM p. 3668
 */
enum HW_INTERRUPTS {
	HW_INT_L2_CACHE = 32,
	HW_INT_CTI_0,
	HW_INT_CTI_1,
	HW_INT_ELM = 36,
	HW_INT_CMU_P,
	HW_INT_SYS_NIRQ1 = 39,
	HW_INT_L3_DBG = 41,
	HW_INT_L3_APP,
	HW_INT_PRCM_MPU,
	HW_INT_SDMA_0,
	HW_INT_SDMA_1,
	HW_INT_SDMA_2,
	HW_INT_SDMA_3,
	HW_INT_MCBSP4,
	HW_INT_MCBSP1,
	HW_INT_SR_MPU,
	HW_INT_SR_CORE,
	HW_INT_GPMC,
	HW_INT_SGX,
	HW_INT_MCBSP2_IRG,
	HW_INT_MCBSP3_IRG,
	HW_INT_ISS5,
	HW_INT_DSS_DSIPC,
	HW_INT_MAIL_U0_MPU,
	HW_INT_DSP_MMU = 60,
	HW_INT_GPIO1_MPU,
	HW_INT_GPIO2_MPU,
	HW_INT_GPIO3_MPU,
	HW_INT_GPIO4_MPU,
	HW_INT_GPIO5_MPU,
	HW_INT_GPIO6_MPU,
	HW_INT_WDT3 = 68,
	HW_INT_GPT1,
	HW_INT_GPT2,
	HW_INT_PT3,
	HW_INT_GPT4,
	HW_INT_GPT5,
	HW_INT_GPT6,
	HW_INT_GPT7,
	HW_INT_GPT8,
	HW_INT_GPT9,
	HW_INT_GPT10,
	HW_INT_GPT11,
	HW_INT_MCSPI4,
	HW_INT_DSS_DSI1 = 85,
	HW_INT_CORTEXA9_CPU0_PMU,
	HW_INT_CORTEXA9_CPU1_PMU,
	HW_INT_I2C1,
	HW_INT_I2C2,
	HW_INT_HDQ,
	HW_INT_MMC5,
	HW_INT_I2C3 = 93,
	HW_INT_I2C4,
	HW_INT_MCSPI1 = 97,
	HW_INT_MCSPI2,
	HW_INT_HSI_P1_MPU,
	HW_INT_HSI_P2_MPU,
	HW_INT_FDIF_3,
	HW_INT_UART4,
	HW_INT_HSI_DMA_MPU,
	HW_INT_UART1,
	HW_INT_UART2,
	HW_INT_UART3,
	HW_INT_PBIAS,
	HW_INT_HSUSB_OHCI,
	HW_INT_HSUSB_EHCI,
	HW_INT_HSUSB_TLL,
	HW_INT_WDT2 = 112,
	HW_INT_MMC1 = 115,
	HW_INT_DSS_DSI2,
	HW_INT_MMC2 = 118,
	HW_INT_MPU_ICR,
	HW_INT_FS_USB = 121,
	HW_INT_FS_USB_SMI,
	HW_INT_MCSPI3,
	HW_INT_HSUSB_OTG,
	HW_INT_HSUSB_OTG_DMA,
	HW_INT_MMC3,
	HW_INT_MMC4 = 128,
	HW_INT_SLIMBUS1,
	HW_INT_SLIMBUS2,
	HW_INT_ABE_MPU,
	HW_INT_CORTEXM3_MMU,
	HW_INT_DSS_HDMI,
	HW_INT_SR_IVQ,
	HW_INT_IVAHD2,
	HW_INT_IVAHD1,
	HW_INT_IVAHD_MAILBOX_0 = 139,
	HW_INT_MCASP1_AXINT = 141,
	HW_INT_EMIF1,
	HW_INT_EMIF2,
	HW_INT_MCPDM,
	HW_INT_DMM,
	HW_INT_DMIC,
	HW_INT_SYS_NIRQ2 = 151,
	HW_INT_KBD_CTL,
	HW_INT_THERMAL_ALERT = 158,
	HW_INT_LAST = 160
};
#define NR_HW_INTERRUPTS HW_INT_LAST




#endif /* ARCH_OMAP4460_EXYNOS_INTERRUPT_TABLE_H_ */
