# Testcomponent code
TACLEBENCH_ST_DIR=taclebench-components/st/

TACLEBENCH_ST_SOURCES_CC = st.cc TaclestComponent.cc
TACLEBENCH_ST_SOURCES_ASM = 
TACLEBENCH_ST_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_ST_DIR)%o,$(TACLEBENCH_ST_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_ST_DIR)%.oS,$(TACLEBENCH_ST_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_ST_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_ST_OBJECTS)

CFLAGS += -DTACLE_ST