# Testcomponent code
TACLEBENCH_COMPLEX_UPDATES_DIR=taclebench-components/complex_updates/

TACLEBENCH_COMPLEX_UPDATES_SOURCES_CC = complex_updates.cc TacleComplexUpdatesComponent.cc
TACLEBENCH_COMPLEX_UPDATES_SOURCES_ASM = 
TACLEBENCH_COMPLEX_UPDATES_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_COMPLEX_UPDATES_DIR)%o,$(TACLEBENCH_COMPLEX_UPDATES_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_COMPLEX_UPDATES_DIR)%.oS,$(TACLEBENCH_COMPLEX_UPDATES_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_COMPLEX_UPDATES_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_COMPLEX_UPDATES_OBJECTS)

CFLAGS += -DTACLE_COMPLEX_UPDATES