# CAN benchmark code
CANBENCHMARK_COMPONENTS_DIR=canbenchmark-components/
CANBENCHMARK_COMPONENTS_SOURCES_CC = CANSimpleTalkerApplication.cc CANSimpleReceiver.cc
CANBENCHMARK_COMPONENTS_SOURCES_ASM = 
CANBENCHMARK_COMPONENTS_OBJECTS = $(patsubst %o,$(OBJDIR)/$(CANBENCHMARK_COMPONENTS_DIR)%o,$(CANBENCHMARK_COMPONENTS_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(CANBENCHMARK_COMPONENTS_DIR)%.oS,$(CANBENCHMARK_COMPONENTS_SOURCES_ASM:%.S=%.oS))

ifeq ($(CONFIG_CAN),true)
	COMPILE_OBJECTS += $(CANBENCHMARK_COMPONENTS_OBJECTS)
	LINKER_OBJECTS += $(CANBENCHMARK_COMPONENTS_OBJECTS)
endif