# Testcomponent code
TACLEBENCH_BITCOUNT_DIR=taclebench-components/bitcount/

TACLEBENCH_BITCOUNT_SOURCES_CC = bitcount.cc bitcnt_1.cc bitcnt_2.cc bitcnt_3.cc bitcnt_4.cc TacleBitcountComponent.cc
TACLEBENCH_BITCOUNT_SOURCES_ASM = 
TACLEBENCH_BITCOUNT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_BITCOUNT_DIR)%o,$(TACLEBENCH_BITCOUNT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_BITCOUNT_DIR)%.oS,$(TACLEBENCH_BITCOUNT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_BITCOUNT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_BITCOUNT_OBJECTS)

CFLAGS += -DTACLE_BITCOUNT