# Event handling code
BENCHMARKING_DIR=benchmarking/
BENCHMARKING_SOURCES_CC =  ResultPrintApplication.cc
BENCHMARKING_SOURCES_CC_UNLINKED = ResultContainer.cc
BENCHMARKING_SOURCES_ASM = 
BENCHMARKING_OBJECTS_LINKED = $(patsubst %o,$(OBJDIR)/$(BENCHMARKING_DIR)%o,$(BENCHMARKING_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(BENCHMARKING_DIR)%.oS,$(BENCHMARKING_SOURCES_ASM:%.S=%.oS))
BENCHMARKING_OBJECTS_UNLINKED = $(patsubst %o,$(OBJDIR)/$(BENCHMARKING_DIR)%o,$(BENCHMARKING_SOURCES_CC_UNLINKED:%.cc=%.o))

COMPILE_OBJECTS += $(BENCHMARKING_OBJECTS_LINKED) $(BENCHMARKING_OBJECTS_UNLINKED)
LINKER_OBJECTS += $(BENCHMARKING_OBJECTS_LINKED)