# Baremetal test code
BAREMETAL_DIR=baremetal/
BAREMETAL_SOURCES_CC =  CATTest.cc

BAREMETAL_SOURCES_ASM = 
BAREMETAL_OBJECTS = $(patsubst %o,$(OBJDIR)/$(BAREMETAL_DIR)%o,$(BAREMETAL_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(BAREMETAL_DIR)%.oS,$(BAREMETAL_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(BAREMETAL_OBJECTS)
LINKER_OBJECTS += $(BAREMETAL_OBJECTS)

CFLAGS += -DCONFIG_BAREMETAL_APPLICATION