##################################
# Cortex-A9 driver compile units #
##################################
CORTEXA9_CACHEMANAGEMENT_DIR=arch/armv7/cortexa9/cachemanagement/
CORTEXA9_CACHEMANAGEMENT_SOURCES_CC = PL310CacheManagement.cc
CORTEXA9_CACHEMANAGEMENT_SOURCES_ASM = 
CORTEXA9_CACHEMANAGEMENT_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(CORTEXA9_CACHEMANAGEMENT_DIR)%.o,$(CORTEXA9_CACHEMANAGEMENT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(CORTEXA9_CACHEMANAGEMENT_DIR)%.oS,$(CORTEXA9_CACHEMANAGEMENT_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(CORTEXA9_CACHEMANAGEMENT_OBJECTS)
LINKER_OBJECTS += $(CORTEXA9_CACHEMANAGEMENT_OBJECTS)