# Testcomponent code
TACLEBENCH_BITONIC_DIR=taclebench-components/bitonic/

TACLEBENCH_BITONIC_SOURCES_CC = bitonic.cc TacleBitonicComponent.cc
TACLEBENCH_BITONIC_SOURCES_ASM = 
TACLEBENCH_BITONIC_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_BITONIC_DIR)%o,$(TACLEBENCH_BITONIC_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_BITONIC_DIR)%.oS,$(TACLEBENCH_BITONIC_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_BITONIC_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_BITONIC_OBJECTS)

CFLAGS += -DTACLE_BITONIC