#####################################
# ARMv7 eventhandling compile units #
#####################################
ARMV7_EVENTHANDLING_DIR=arch/armv7/eventhandling/
ARMV7_EVENTHANDLING_SOURCES_CC = 
ARMV7_EVENTHANDLING_SOURCES_ASM = EventHandler.S
ARMV7_EVENTHANDLING_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(ARMV7_EVENTHANDLING_DIR)%.o,$(ARMV7_EVENTHANDLING_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(ARMV7_EVENTHANDLING_DIR)%.oS,$(ARMV7_EVENTHANDLING_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(ARMV7_EVENTHANDLING_OBJECTS)
LINKER_OBJECTS += $(ARMV7_EVENTHANDLING_OBJECTS)