# Testcomponent code
TACLEBENCH_FIR2DIM_DIR=taclebench-components/fir2dim/

TACLEBENCH_FIR2DIM_SOURCES_CC = fir2dim.cc Taclefir2dimComponent.cc
TACLEBENCH_FIR2DIM_SOURCES_ASM = 
TACLEBENCH_FIR2DIM_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_FIR2DIM_DIR)%o,$(TACLEBENCH_FIR2DIM_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_FIR2DIM_DIR)%.oS,$(TACLEBENCH_FIR2DIM_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_FIR2DIM_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_FIR2DIM_OBJECTS)

CFLAGS += -DTACLE_FIR2DIM