# Testcomponent code
TACLEBENCH_FILTERBANK_DIR=taclebench-components/filterbank/

TACLEBENCH_FILTERBANK_SOURCES_CC = filterbank.cc TaclefilterbankComponent.cc
TACLEBENCH_FILTERBANK_SOURCES_ASM = 
TACLEBENCH_FILTERBANK_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_FILTERBANK_DIR)%o,$(TACLEBENCH_FILTERBANK_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_FILTERBANK_DIR)%.oS,$(TACLEBENCH_FILTERBANK_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_FILTERBANK_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_FILTERBANK_OBJECTS)

CFLAGS += -DTACLE_FILTERBANK