
###############################
# Exynos4412 generic compile units #
###############################
EXYNOS4412_BOOT_GENERIC_DIR=arch/armv7/exynos4412/boot/
EXYNOS4412_BOOT_GENERIC_SOURCES_CC = initOS.cc
EXYNOS4412_BOOT_GENERIC_SOURCES_ASM =
EXYNOS4412_BOOT_GENERIC_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(EXYNOS4412_BOOT_GENERIC_DIR)%.o,$(EXYNOS4412_BOOT_GENERIC_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(EXYNOS4412_BOOT_GENERIC_DIR)%.oS,$(EXYNOS4412_BOOT_GENERIC_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(EXYNOS4412_BOOT_GENERIC_OBJECTS)
LINKER_OBJECTS += $(EXYNOS4412_BOOT_GENERIC_OBJECTS)


SUB_MODULES =

include $(patsubst %,\
$(EXYNOS4412_BOOT_GENERIC_DIR)%/module.mk,$(SUB_MODULES))
