# Testcomponent code
STRESSTEST_DIR=stresstest/
STRESSTEST_SOURCES_CC = StressTestInitiator.cc

STRESSTEST_SOURCES_ASM = 
STRESSTEST_OBJECTS = $(patsubst %o,$(OBJDIR)/$(STRESSTEST_DIR)%o,$(STRESSTEST_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(STRESSTEST_DIR)%.oS,$(STRESSTEST_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(STRESSTEST_OBJECTS)
LINKER_OBJECTS += $(STRESSTEST_OBJECTS)

CFLAGS += -DCONFIG_STRESSTEST_COMPONENTS