# Testcomponent code
TACLEBENCH_JFDCTINT_DIR=taclebench-components/jfdctint/

TACLEBENCH_JFDCTINT_SOURCES_CC = jfdctint.cc TaclejfdctintComponent.cc
TACLEBENCH_JFDCTINT_SOURCES_ASM = 
TACLEBENCH_JFDCTINT_OBJECTS = $(patsubst %o,$(OBJDIR)/$(TACLEBENCH_JFDCTINT_DIR)%o,$(TACLEBENCH_JFDCTINT_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(TACLEBENCH_JFDCTINT_DIR)%.oS,$(TACLEBENCH_JFDCTINT_SOURCES_ASM:%.S=%.oS))


COMPILE_OBJECTS += $(TACLEBENCH_JFDCTINT_OBJECTS)
LINKER_OBJECTS += $(TACLEBENCH_JFDCTINT_OBJECTS)

CFLAGS += -DTACLE_JFDCTINT