
###############################
# OMAP4460 generic compile units #
###############################
OMAP4460_BOOT_GENERIC_DIR=arch/armv7/omap4460/boot/
OMAP4460_BOOT_GENERIC_SOURCES_CC = initOS.cc
OMAP4460_BOOT_GENERIC_SOURCES_ASM = 
OMAP4460_BOOT_GENERIC_OBJECTS = $(patsubst %.o,$(OBJDIR)/$(OMAP4460_BOOT_GENERIC_DIR)%.o,$(OMAP4460_BOOT_GENERIC_SOURCES_CC:%.cc=%.o)) $(patsubst %.oS,$(OBJDIR)/$(OMAP4460_BOOT_GENERIC_DIR)%.oS,$(OMAP4460_BOOT_GENERIC_SOURCES_ASM:%.S=%.oS))

COMPILE_OBJECTS += $(OMAP4460_BOOT_GENERIC_OBJECTS)
LINKER_OBJECTS += $(OMAP4460_BOOT_GENERIC_OBJECTS)


SUB_MODULES =

include $(patsubst %,\
$(OMAP4460_BOOT_GENERIC_DIR)%/module.mk,$(SUB_MODULES))
